php:
  build: .
  container_name: api-slim-php
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./html:/var/www/html
  links:
    - mysql

mysql:
  container_name: api-slim-mysql
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=cats